### ISSUE TITLE
No reference found on non-empty git history

### ISSUE THREAD

**Issue by CodingJonas** [aevea/commitsar#230]
I run this project on the latest version in my gitlab ci pipeline on different branches and experience some weird behaviour:
On some branches it works fine, while on others it throws this error:
```
$ commitsar -v
Starting analysis of commits on branch HEAD
reference not found
```
There is a git history available:
```
 $ git --no-pager log --oneline
c7c1561 chore: commit
5710afe chore: another commit
bea536b Merge branch 'branch' into 'develop'  <-- This is the latest commit to the branch I branched out from
236c3dc ci: add stuff
```

I'm not too familiar with the code of this project, how can I debug this further?

**Comment by fallion** [comment]
Hi @CodingJonas,

I'll add some additional debug tools tonight or tomorrow. After that I'll help with any issues you might have :)

**Comment by fallion** [comment]
@CodingJonas What is your git_depth variable setting?

**Comment by fallion** [comment]
My guess right now is that it can't get to the commit object here: https://github.com/aevea/commitsar/blob/a3f6d2da0ac2a0e88f2a7a66dbbc91907bfdf26d/internal/root_runner/run.go#L51

**Comment by fallion** [comment]
@CodingJonas can you try adding `git fetch origin master` before running commitsar?

**Comment by CodingJonas** [comment]
You are right, when I set the `GIT_DEPTH` variable it works. I tried out different values: 1,2,10
It always worked, but it checked a lot more commits than only the ones of the current branch. I'm not super sure what the variable is doing. Would you recommend to run this job with the `GIT_DEPTH` variable set?

**Comment by fallion** [comment]
For now it's a quick fix. I'll look into fixing this.

So what GIT_DEPTH does is that it's the amount of full commit objects it will pull. This is useful on big repositories because you prevent pulling in extra data that you won't need. However the current implementation of the diff engine that commitsar uses relies on these full objects. I will try to find a way to either pull or completely skip this step.

**Comment by CodingJonas** [comment]
Yes, I set GIT_DEPTH to 0, which defaults to fetch the entire history, so everything is working. Thank you!

**Comment by lfilho** [comment]
Hey, I'm using the Github action and having this error. Please see my comment and more details at https://github.com/aevea/commitsar/issues/167#issuecomment-644976149
