### ISSUE TITLE
Option to enforce scope in commit title

### ISSUE THREAD

**Issue by kowalczykp** [aevea/commitsar#325]
Slightly related to #213 

It'd be great if commitsar could enforce the existence of the scope part in the commit title. The scope is considered optional by the conventional commits spec, but that feature would be very beneficial to repositories requiring stricter checks. The next step could potentially be, restricting the allowed scopes to a configurable list.

Let me know, if that makes sense and if you'd be interested in such a feature. I'd be happy to PR it.

**Comment by fallion** [comment]
I think this could be a cool addition to the configuration file. Feel free to open a PR :) I am in the process of reworking the flow a little so if you could wait until Wednesday then that would be great :)

**Comment by fallion** [comment]
All yours :)

**Comment by fallion** [comment]
@kowalczykp hey,

Have you had a chance to look at this?

**Comment by kowalczykp** [comment]
hey @fallion, sorry for the late answer. I've sat down to this today, and have a working code ready. I will add some tests, clean up the code, and will create PR later today with some points to discuss
